% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Dec-2021 13:29:07
%  MATLAB version: 9.11.0.1769968 (R2021b)
% -------------------------------------------------------------------
saveVarsMat = load('Semantic_segmentation_Net.mat');

net = saveVarsMat.net; % <1x1 DAGNetwork> unsupported class

clear saveVarsMat;
